/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.7 */
/* Sun Feb 16 18:00:26 2025 */

/* parameterized module instance */
PLL24M __ (.CLKI( ), .CLKOP( ));
