/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.7 */
/* Sun Mar 02 14:43:36 2025 */

/* parameterized module instance */
pll __ (.CLKI( ), .CLKOP( ));
